package backend.interpreter;

import backend.*;
import intermediate.*;
import message.*;

import static message.MessageType.INTERPRETER_SUMMARY;;

public class Executor extends Backend {
	/*
	 * Process the intermediate code and the symbol table generated by the
	 * parser to execute the source program.
	 * @param iCode the intermediate code.
	 * @param symTab the symbol table.
	 * @throws Exception if an error occurred.
	 */
	public void process(ICode icode, SymTab symTab)
	throws Exception{
		long startTime = System.currentTimeMillis();
		float elapsedTime = (System.currentTimeMillis() - startTime)/1000f;		//elapsed execution time
		int executionCount = 0;		// number of statements executed
		int runtimeErrors = 0;		// number of runtime errors
		
		//Send the interpteter summary message.
		sendMessage(new Message(INTERPRETER_SUMMARY,
				new Number[] {executionCount,
						runtimeErrors,
						elapsedTime}));
	}
	
}
